### ISSUE TITLE
Volume control display doesn't respect max volume setting

### ISSUE THREAD

**Issue by rretsiem** [volumio/Volumio2-UI#231]
Setting the max volume to e.g. 50 leads to a weird volume control display.

The round label still shows <nn>/100 -> should be <nn>/50, also the round slider can be pulled to 100 but jumps back to the max 50, maybe the round slider should be set to respect the setting as well and at "full circle" it's always at max volume.

Same on the mobile view on iPhone the vertical sliders always say <nn>/100 and can be adjusted to 100.

Latest official release 2.001 with IQaudio DAC

**Comment by xipmix** [comment]
It might help to have an additional indicator on the volume control ui element that shows the current max volume setting, like a red or white line drawn across the slider, pointed at the centre of curvature. Otherwise, some kind of marker just outside the slider track? This would make it clearer what is going on when you try to set a volume higher than the max and the slider snaps back as described above.

**Comment by Jotam** [comment]
@xipmix Very good idea. +1

**Comment by xipmix** [comment]
See also volumio/Volumio2#465
