### ISSUE TITLE
Using GUI through firewall, NAT, etc

### ISSUE THREAD

**Issue by earlchew** [volumio/Volumio2-UI#258]
As a user, I want the volumio GUI to use a single TCP port from my browser, so that I can use volumio in a corporate environment where TCP ports are administratively constrained.

To simulate my corporate environment, I use a ssh tunnel from localhost:5000 to connect to my volumio appliance running elsewhere. The initial connection goes well, and then the GUI gets stuck at this point:

```
GET /app/i18n/locale-en.json HTTP/1.1
Host: 127.0.0.1:5000

GET /api/host HTTP/1.1
Host: 127.0.0.1

GET /app/local-config.json HTTP/1.1
Host: 127.0.0.1:5000

GET /socket.io/?EIO=3&transport=polling&t=LcVn0Fi HTTP/1.1
Host: 127.0.0.1:3000
```

The corresponding GUI code appears to be:

```
        socketResolver: ($rootScope, $http, $window, socketService, ripperService, modalListenerService,
            toastMessageService, uiSettingsService, updaterService) => {
          let localhostApiURL = `http://${$window.location.hostname}/api`;
          return $http.get(localhostApiURL + '/host')
            .then((response) => {
              console.info('IP from API', response);
              $rootScope.initConfig = response.data;
              socketService.host  = response.data.host;
              socketService.host2 = response.data.host2;
            }, () => {
              //Fallback socket
              console.info('Dev mode: IP from local-config.json');
              return $http.get('/app/local-config.json').then((response) => {
                socketService.host  = response.data.localhost;
                // socketService.host = '192.168.0.90';
                // socketService.host2 = '192.168.0.9';
              });
            });
        }
```

What would be the approach to have the GUI continue to use `$window.location` for GUI interaction with the back end?

Continuing to use the connecting `$window.location` would also allow other interesting configurations such as a https proxy sitting ahead of the appliance: http://serverfault.com/questions/486042/use-apache-as-a-https-to-http-proxy

**Comment by earlchew** [comment]
https://github.com/earlchew/volumio2-UI/commit/b57b00805bf44545ab722f6a9408d8eb42c7397b

Something like the above achieves the effect I think is necessary.

**Comment by earlchew** [comment]
I've done a fair amount of work to enable this functionality: https://github.com/earlchew/volumio2-UI/tree/issue-258-02

Before I issue a pull request, I'd like to know if there's any additional testing worth performing.

While performing these tests, I patched a defect arising from an upstream issue: https://github.com/earlchew/volumio2-UI/commit/87cc7a143fdba5adff6eb52f7bf71269b68e27ba

Here are the scenarios that I have tested:
* Split operation where the GUI is served at http://192.168.1.90:3000, and the backend is served at http://127.0.0.1:3000
* Operation where the complete volumio appliance comprising the backend and GUI is served at the root of a site: http://127.0.0.1:3000

I have also tested the following scenarios that are more relevant to https://github.com/volumio/Volumio2-UI/issues/259:
* Operation where the complete volumio appliance is proxied at http://192.168.1.90/caruso using HTTP only, and using HTTP and WebSockets
* Operation where the complete volumio appliance is proxied at https://192.168.1.90/caruso using HTTP only, and using HTTP and WebSockets

**Comment by volumio** [comment]
Interesting...  Could you explain a bit more how you did that? 
Also, I would test if switching device (with the UI device switching in the playback tab) does work

**Comment by earlchew** [comment]
@volumio wrote:
> switching device (with the UI device switching in the playback tab) 
Would you explain this scenario in a little more detail for me? I do not completely understand this configuration, and how to carry out the use case.

**Comment by volumio** [comment]
If you have more devices on the same network (we advertise volumio service via mdns), you will see each device name, curren playing info and albumart on the playback tab.

**Comment by earlchew** [comment]
I don't have the right equipment in the right location to test this feature, but here are my observations:
* The mdns runs in the back end. I do not see any mdns code in the GUI repository.
* I found the volumiodiscovery plugin in the repository for the back end
** The volumiodiscovery plugin seems to assume wlan0, which is not always true. It is possible to run volumio over other interfaces, such as eth0, etc.
** The volumiodiscovery plugin connects to the discovered devices over the backend network, and provides their IP addresses to the GUI
* The GUI provides a MultiRoomService to manipulate the discovered devices, but uses the IP addresses provided by the GUI

This means that operating the Volumio in a remote configuration such as I have described will not work because the GUI is being provided the private backend IP addresses, but the GUI only has access to the single public front end IP address.

The way to make this work is to require that the GUI only interact with the front end IP address that the user typed to provide the browser with the site location, and then have the backend Volumio device forward the request to the other backend device that is the target of the request.

**Comment by CherryDT** [comment]
Why was this closed? It is still not working.

**Comment by rramstad833** [comment]
> Why was this closed? It is still not working.
> Volumio seems to try to access the LAN IP from the website which of course won't work if accessed through a reverse proxy from the outside.

I too am very confused in that my testing earlier today indicates that the GUI will not work when accessed through a port forwarding type of configuration either i.e.

Using device on WAN 192.168.x.x and trying to access Volumio running on LAN 10.55.0.159
(works perfectly within the LAN)

WAN to LAN gateway at 192.168.0.2

Gateway has NAT forwarding
192.168.0.0/16 port 17999 forwards to 10.55.0.159 port 3000 (also tried 80)

Within Chrome on a WAN device I get spinning circle forever at gateway:17999
Very clearly is loading part of the Volumio GUI -- I can see buttons at the bottom and Volumio at the top, but the spinning circle of dots spins forever i.e. the GUI can't load, presumably because the system is confused because of the forwarded port, it doesn't know what to call to load the interface.

**Comment by volumio** [comment]
It has been closed because this feature is supported via MyVolumio remote connection (which has been designed to work behind firewalls and not on the same network).
Getting this to work manually requires extensive rework of code and IP address hardcoding.
I would suggest to give myvolumio a go and navigate to your devices via myvolumio.org ;)

**Comment by rramstad833** [comment]
Hi, I'm confused.  You are saying that I have to pay for a subscription to
access my Volumio device from my local WAN, simply because the GUI is
written so poorly that it won't load properly through a port forward?

If that's correct, this is an obnoxious response.  I'll find something that
runs on my Raspberry Pi hardware that doesn't require a paid subscription
for basic functionality.

**Comment by volumio** [comment]
No need to be angry there and disqualify things that you seem to not understand... 
Simply the UI has been coded taking into account what 99,99% of users might need. And, as you surely know, websockets require an endpoint to work with. We simply assume that if you can reach the UI on some IP, also the backend is on the same IP as well.

That being said: we developed an easy solution that work in all other edge cases. You're free to use it if you want, otherwise you're also free to dig into the code and hardcode your IP in the rest api call that sets the websocket endpoint.

**Comment by CherryDT** [comment]
Wouldn't it be enough to use `location.origin` instead of manually assembling `http://` and the IP? (Or if it's done on the server, use the request's `Host` header instead of the IP...)

**Comment by volumio** [comment]
@CherryDT location.origin would not work, since we might be on multiple IP addresses (eth0 and wlan0). Our UI code requests available endpoints to the BE and will connect to the first available. Upon failure, it will also automatically fallback to the next available.

**Comment by rramstad833** [comment]
A solution was already coded (mentioned earlier in this thread) but has not
been absorbed into Volumio.

It's fine, I'll just switch to a different audio software.  I had been
planning on making a donation to Volumio but I'm not going to be held
hostage to an annual fee.

It drives me absolutely insane when free software goes down this path.  I
am sure that some of the people who contributed to Volumio over the years
would be offended to see this outcome -- especially the individual above
who provided code patches that should solve my case, as well as other cases.

**Comment by volumio** [comment]
The solution mentioned above was not merged because it simply did not solve anything...

Nobody wants to make you hostage: you're free to dig into the code, edit it, do what you like with it etc. This is why we release Volumio as an open source project.

Want an easy solution? we made it, ready to use without any hassle.
Want to fix your edge case without paying? you're free to do so, and hopefully share your experience with others.

Re Free software: most people tend to forget that running a project like this requires a) time, b) money, c) skilled people to work on it. We decided to do MyVolumio and other things to get revenues to keep the project going. The amount of donations we receive in a year won't cover even hosting costs...
If this drives you insane, then you probably don't consider all the above.

**Comment by rramstad833** [comment]
How can you say the solution above doesn't accomplish anything when it
fixed four different problems and indirectly would have fixed mine as well?

Just keep closing bugs that are actual bugs and telling yourself you are
doing the right thing by refusing to integrate code and solutions that
other people are providing to you.

**Comment by volumio** [comment]
If you refer to this: https://github.com/earlchew/volumio2-UI/commit/b57b00805bf44545ab722f6a9408d8eb42c7397b

Maybe this would solve your scenario, but it will break:
- Local browser support
- Auto-switching from wifi\eth

If it fixes your issue, then use it. Why still complaining on things you don't totally understand?
That's my last message on this. Bye.

**Comment by rramstad833** [comment]
I just love when someone says they run a community software project, an
alternative to corporate things like Sonos, and then they just aren't
interested in solving real problems or more accurately will only solve them
if they are paid.

**Comment by Ramblurr** [comment]
I installed Volumio half an hour ago, and landed here after trying to figure out the necessary settings to add volumio to my local nginx reverse proxy to get https support and a nice domain `volumio.myhouse.com`, but of course you get:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<ip address>/socket.io/?EIO=3&transport=polling&t=N2VpIaH. (Reason: CORS request did not succeed).`

..because volumio has been coded to always use the local ip address as the hostname for the API/web socket endpoint.

I realize its volumio's project and they have the final say in what gets merged into their open source project. And despite some flak here from other people, @volumio has responded kindly and reasonably.

In the end though, I want control over whats running on my home network, and I want to be able to configure it the way I want. Perhaps someday I, or someone else will find the time to come up with a maintainable solution to this problem if volumio doesn't implement it. But in the mean time.. back to picoreplayer.

Just my 2¢.

**Comment by CherryDT** [comment]
> @CherryDT location.origin would not work, since we might be on multiple IP addresses (eth0 and wlan0). Our UI code requests available endpoints to the BE and will connect to the first available. Upon failure, it will also automatically fallback to the next available.

I don't understand this answer.

Your UI code is running in the browser. The browser already knows from what URL the page was loaded. Your UI code also knows, since the browser provides this information in `location`. For example, on this page `location.origin` gives you `https://github.com`. If I connect to Volumio via `volumio.local`, I'll get `http://volumio.local`, and if I connect via, say, IP 10.0.0.1, I get `http://10.0.0.1`, and if I connect via a reverse proxy I get, say, `https://volumio.myhouse.org` like in the example that Ramblurr just wrote.

So, it doesn't matter what interface or domain or IP or whatever is used, since you'll always get the right protocol and domain/IP at that point. (Actually, you wouldn't even have to use _any_ domain/IP, since you could just initiate a connection to `/socket.io` as relative URL and the browser would figure it out.)

So I think the solution would be to simply remove the protocol+hostname part at all (or replace it with `location.origin`) and everything would work for everyone regardless of any proxying or port forwarding.

**Comment by rramstad833** [comment]
@CherryDT Precisely the point I was trying to make, there are at least two trivial approaches that don't require much work and would result in code that was clearer, easier to maintain, and more flexible.

It would be great if someone wanted to dig into this a bit and get the changes merged into the main flow of code.  I don't know if that is realistic as the author of Volumio seems to be more interested in revenue via MyVolumio.

**Comment by CherryDT** [comment]
Looking at the code, I see that at https://github.com/volumio/Volumio2-UI/blob/2f0519c838b1c449ea3ffc542c0178759ca29663/src/app/services/device-endpoints.service.js#L37 the API (which _is_ accessed via `location.hostname`! however via HTTP as fixed protocol) is used to fetch a list of hosts (which are those interface IPs) and then uses those for the socket connection.

I believe this step is completely unnecessary, it could just return the same host that is used to access the API in the first place! (This one is always right.)

But, this showed that there are a few more fixes which should be good: `http://` shouldn't be hardcoded as protocol when accessing the API.

**Comment by volumio** [comment]
Thinking a bit more about  it, a possible solution to your case is simply to add a local-config.json file on the UI path (or on a locally built ui) which points to the host you want to use.
Would that be viable?

The reason why we use the API over $window.location.hostname is that some devices might have 2 different IPs for wifi and eth. By using the API, the UI receives both of them. So in case one of the 2 becomes unavailable, the UI will switch host to the other one.
This happens for example when you configure wifi and then you remove ethernet: with the approach of hostname, the UI will not automatically recover from such situation

**Comment by CherryDT** [comment]
Hm, I see what you mean now. In this case, how about just adding the current hostname to the list of socket hosts? (And ideally using the browser's protocol (http/https) instead of hardcoding http, then it'd also work with a reverse proxy that does SSL termination.)

**Comment by volumio** [comment]
@CherryDT Yep, glad you understood the scenario now, and glad that we both had the same idea. I agree this can be the solution (also like that we don't hardcode protocol). Only thing I will need to think is if that will conflict with the myvolumio remote host situation (but in case, we can handle that).

**Comment by volumio** [comment]
@CherryDT if you like, please do a PR with the aforementioned method and I'll gladly review it and merge if ok

**Comment by DragRedSim** [comment]
Having had a look at this, a potential issue arises where port forwarding is in use to redirect towards the Volumio WebUI. The call to the getLocalSocketHosts() does not take into account the port being used, and thus it attempts to access the API over port 80; if/when this fails, it then falls back to the local-config.json stated.

I don't have a build environment set up, so I can't quickly test; but I feel that the following (once edited for syntax; treat this as purely pseudocode) is likely to work. The following replaces lines 37 through 39 of Volumio2-UI/src/app/services/device-endpoints.service.js.

```
  getLocalSocketHosts() { 
   if ($.(this.$window.location.port) != "") {
     let localhostApiURL = `http://${this.$window.location.hostname}:$.(this.$window.location.port)/api`; 
   } else let localhostApiURL = `http://${this.$window.location.hostname}/api`; 
   return this.$http.get(localhostApiURL + '/host')
```

I've wrapped the statement in the if block as some browsers return a blank string when the port for which the request being made on is equal to the standardised port for that protocol.

**Comment by DaniilMir** [comment]
I just needed to have an external access only to Volumio. 
For me it worked by a simple hard-coding an IP Address : 

File : restapi.js 

```
          if (hostsarray.length > 1) {
//            return res.json({host: hostsarray[0], host2: hostsarray[1]});  
			  return res.json({host: 'XXX.XXX.XXX.XXX', host2: hostsarray[1]}); // A hardcoded host IP to work from the external network
          } else {
//            return res.json({host: hostsarray[0]});
			  return res.json({host: 'XXX.XXX.XXX.XXX'});
          }
```
