### ISSUE TITLE
Plugin upload hangs with certain filenames

### ISSUE THREAD

**Issue by LifelessDead** [volumio/Volumio2-UI#299]
Plugin upload hangs when uploading certain file names.

Example: _auto_play (1).zip_
This will work when renamed to _auto_play.zip_ before upload.

**Comment by xipmix** [comment]
I took a look at the backend code and I think I see some things that could be improved. 
I'd like to be able to reproduce the issue; can you tell me how/where you obtained auto_play.zip?

**Comment by volumio** [comment]
To replicate the error, just download any plugin
for example 
https://github.com/volumio/volumio-plugins/blob/gh-pages/plugins/volumio/armhf/music_service/spotify/spotify.zip?raw=true

and rename it to spotify(1).zip

**Comment by xipmix** [comment]
This happens because of the exec to do the wget in pluginmanager's installPlugin function. The URL is not quoted and so the shell loses its lunch when it sees a scary parenthesis. 

When trying to fix this I rediscovered why ever using the user's input when doing anything with file uploads is a Bad Idea; it was necessary to generate a name internally and send the input stream to that. Otherwise I could also make the DecompressZip() call explode with all kinds of pretty colours.
