### ISSUE TITLE
[privacy] Remove or opt-in google analytics tracker

### ISSUE THREAD

**Issue by arthurlutz** [volumio/Volumio2-UI#310]
In the last version of volumio2 a google analytics tracker was introduced with no (or little) warning. I think this tracking it problematic. I would suggest (in the order of preference) : 

1) removing it
2) have an opt-in setting with a "help volumio development by enabling a usage tracker, thanks a bunch, you're awesome!"
3) have an opt-out setting with a message such as "hey, by default volumio tracks your usage using google analytics, your data is being used for X, and Y by the developers (and google)".

In the case of 3) I think some words of warning should appear on the download page of the volumio project and an update message for already existing users. 

The changeset that introduces this is https://github.com/volumio/Volumio2-UI/commit/0d6cba93c447ea6f3b64c98acc5fbeb27f899acb

An alternative approach which would diminish the problem and resistance to this type of tracker would be to use an open source, self-hosted alternative to google analytics such as https://piwik.org/ for example.

**Comment by volumio** [comment]
Thanks for the hint, I did not imagine google-analytics would raise a concern (it just tracks daily usage statistics), and its already covered by our privacy policy.
However, I understand your concerns and I'm taking a look at piwik, which could be a privacy-sensible alternative, since it should provide us with what we need without notifying google. What do you think

**Comment by xipmix** [comment]
It would help if the purpose of gathering the data was explained a bit more - it seems you are interested in tracking how many active installations? I feel there is far too much monitoring like this on 'teh internetz' just because it is possible, without a clear purpose for the data. I'm not saying that's the case here, but that I feel uninformed about what is collected and how it can be used.

**Comment by marianol** [comment]
In my opinion something like piwik is worst than Google Analytics. This puts the legal burden on @volumio or whoever hosts the information to keep that secure. And in my case I trust Google more for that no offense Michelangelo. Also note that Github uses GA also so if that is a concern :)

With that said, I do believe that option 2 to 3 are rightful options to have.

**Comment by volumio** [comment]
Mariano is also right. I think what we're going to is experiment with piwik on some lateral service (like just the forum, giving notice), and keep on using GA (already covered by privacy policy) and state clearly in the Credits page which information we're collecting and for what purpose. 
Would that be a reasonable approach in your opinon?

**Comment by arthurlutz** [comment]
@volumio if I can opt-in or opt-out sure... 

@marianol the difference, in my opinion is not about securing those statistics, but more a question of decentralizing them. The cost/benefit ratio of an entity having to hack a piwik instance is too high. In the other case, our friend google (and his partners) have access to all the data and can correlate it to many other sources... (I encourage anyone who has questions about privacy to at least one try out the admin side of google analytics to understand this).

**Comment by marianol** [comment]
@arthurlutz Yes I get it, and understand your point. But I still prefer to be tracked by Google commercial product than to someone running and hosting piwik.
That is why I ended saying that the opt-out is the best for privacy concerns.

I have worked with GA for a long time and know how they collect data and how the admin and API side not only the standard but also the premium GA 360.

**Comment by volumio** [comment]
Is someone willing to help on this? 
The opt-out feature is integrated in the angular module we're using https://github.com/revolunet/angular-google-analytics

**Comment by kehugter** [comment]
The shock of GA in my `192.168` was like having a cheap IoT camera, mounted inside my toilet, steaming live on Youtube. Thanks for making it an opt-up.

To out-out right away, or just don't have it listed in NoScript,

`ssh volumio@volumio_ip "sed -i 's/google-analytics\.com//g' /volumio/http/www/index.html"`

**Comment by volumio** [comment]
@kehugter Do you even know that having GA on Volumio is like visiting any other website in the world with google analytics on? 
And that the fact that it's hosted on your LAN does not change a thing? It's always js running on your browser, 192.168 is simply pointless.

And when I mean every website, I also mean github (which you visited to post your comment), which has google-analytics enabled... The very same js script...
So please...

**Comment by kehugter** [comment]
> every website

Yes, that's exactly the point. Every website, and slowly every app, service, ebook, gadget, etc is tracking the users, to feed one or the other data kraken.

Analytics are a great tool for development, I agree. I don't have any expectation of privacy when I visit a 3rd party website, that's why I have several layers of ad/tracking/spyware blocking. But I expect that my own hardware doesn't spy on me, or at least has the decency of warning me about it. That's why `192.168` matters.

**Comment by volumio** [comment]
Then if you could send a PR with an opt-in \ opt-out mechanism we will be glad to integrate it

**Comment by kehugter** [comment]
I can't promise results, but I'll give it a try tonight.

**Comment by dup2** [comment]
I fully support @kehugter here, it's about privacy - I expect software to not track me by default, it should give me at least the choice. This is not a website but a local installation in my private network.

**Comment by volumio** [comment]
@kehugter we install it trough bower

**Comment by kurtommy** [comment]
Hi guys I'm the lead dev of this repo and like you, I care a lot about my privacy.
I appreciate that this issue is raised. This is an important topic and we'll take care to inform the user that we are using analytics. 

In general there is a lot of confusion out about tracking software / privacy etc...

Some clarifications:
Analytics is only a kind of tracking software and it's a product intended to be used by the developers that are going to install it on the website or IoT device, not by Google itself.

You have to consider the way your data are managed, aggregated, parsed, elaborated and for which scope / intention they are used.
We have added analytics only to build a better UI, we'd like to consider the average viewport, time required to load the UI, network connections, common devices, locations to provide better CDN solutions etc...
We are not selling or sending this data to third parties. 

I've worked and i'm still working for companies that make an heavy usage of tracking software. And you can't immagine how many things are tracked while you navigate a website, there are hundred of tags fired every couple of seconds. Most of this code is made in house and the usage is explained in terms & cond. (who is going to read it for every website?)
You should care about your privacy when you are using FB, Twitter, Gmail, Gmaps ... they are retrieving a massive amount of data that are used to make assumptions (and are very realistic assumptions) about your personal life / habits / and preferences. They could know which flavour of ice cream you like even if you haven't talk about it on a single webpage. 
This is scary and this really touch your privacy.

About your private network: 
If your PI is offline analytics is dead, if your PI is online you have installed on it a piece of software  that uses analytics, installing Volumio on your PI you are installing a web server (with Node) and a website (with Angular), the Volumio UI. That's it.
Analytics is activated only when you navigate to the Volumio UI. It's not actived by default when you turn on the PI.
I've never seen any website asking to the user if he'd like to deactivate analytics :)

Keep in mind that analytics is installed inside billions of website and the data that Volumio could send to Google servers are exactly the same that you have already sent while browsing another website through your browser/device.

Again, we are going to inform the user in the next release of Volumio about GA.

**Comment by dup2** [comment]
> We are not selling or sending this data to third parties.

In this case, google is the third party. By linking to their analytics script, you provide them valuable data and improve their profiling. Maybe I'm the only one here not using FB, Twitter, G* whatever or/and actively blocking tracking and tagging sites and as such, I have a completely different view in most points you described above - just because everybody does it, does not make it any better, though.

However, I'm not here to argue about this but just ask for opt-in/opt-out for the tracking part.

Btw, I ❤️ your application and think it's perfect as an audio player on the PI!

**Comment by kehugter** [comment]
Appreciated, @kurtommy.

@volumio 
I grep and grep but `angular-google-analytics` (nor `AnalyticsProvider` or `UA-92970181-1` other than in `index.html`) just doesn't show up. Double-checked the `bower.json` manually, nada. Tried on `master` and `development` branches, on a clean cloned repo and after installing all dependencies.

**Comment by volumio** [comment]
@kehugter sorry, my bad.
You can see how GA is loaded from the inclusion commit:
https://github.com/volumio/Volumio2-UI/commit/0d6cba93c447ea6f3b64c98acc5fbeb27f899acb

**Comment by opnwrt4lede** [comment]
@kurtommy 
> About your private network:
If your PI is offline analytics is dead, if your PI is online you have installed on it a piece of software that uses analytics, installing Volumio on your PI you are installing a web server (with Node) and a website (with Angular), the Volumio UI. That's it.
Analytics is activated only when you navigate to the Volumio UI. It's not actived by default when you turn on the PI.

If this one is true, a browser plugin like 'ublock origin' should be sufficient to **block** all network traffic volumio want's to sent to google - right?

I would be happier if I can disable the _google worm_ directly in volumio. Also the load and scripts should be reduced by deactivating calling the _big brother_ which should also leads to a faster and more pleasant adventure with volumio.

**Comment by acidicX** [comment]
It should be pretty straight forward to create a volumio plugin that removes the code inside the HTML on every start, right? This would mean it is also deleted after every upgrade. I'd try it but maybe someone can give me some insights beforehand, if there are any pitfalls I have not considered correctly (e.g. missing user rights to modify the html? @volumio)

Btw @dup2, you are not the only one :) I'm 100% with you on this.

**Comment by volumio** [comment]
@acidicX this is the wrong way to do it, since it means that your UI will not be upgraded since you're writing it do disk and this will override what comes in the squashfs.

This is the only proper way to cope with this, as explained here https://github.com/volumio/Volumio2-UI/issues/415 :

- The setting must be stored on BE for persistence of the choice among all FEs
- We need to dynamically load the library based on such choice, therefore we need to change where the library gets loaded (hopefully it will still work when enabled) and find a way to retrieve the setting while not causing performance bottlenecks...

**Comment by pidiet** [comment]
I would also would like to see a google-free version of volumio!

**Comment by jalr** [comment]
Saw volumio is now using google analytics. Without opt-in. I'm through with volumio.

**Comment by STPKITT** [comment]
I'm also leaving Volumio because of this.

**Comment by buzuck** [comment]
I am currently manually patching every release, and un-patching it for the next one as there is some kind of integrity check.

I'm more and more inclined to leave Volumio because of this. And now, I just saw the apparition of a new tracker here : `connect.facebook.com` :angry:

A tracker-free version shouldn't be that hard to implement, and I don't recall seeing any prompt from Volumio before it installing crappy services on my hardware... :disappointed:

**Comment by volumio** [comment]
We understand all the privacy concerns you guys have, and your reports are not going to be unanswered...
We have an opt-out feature in the work since long time (there is a branch on the UI... we just miss the BE code).

Please also consider that to improve Volumio, we need some sort of usage data to understanding which features are most used, on which devices etc. 
So, while some might think it's a privacy concern, in fact, we use those data to make Volumio better (and we don't do anything else with those datas).

As I said many times, if someone if willing to help develop this, please let us know. We are more than happy to merge any code in this direction.

@buzuck unfortunately there is no facility to auto-deploy scripts after updates...

**Comment by acidicX** [comment]
> Please also consider that to improve Volumio, we need some sort of usage data to understanding which features are most used, on which devices etc.

@volumio You neither need GA nor Facebook for that. A lot of tools just ask for it at the first start and send them to a self-hosted logging server that is not run by Google. And even if, you can decline it.

> So, while some might think it's a privacy concern

No. It **is** a privacy concern. In the EU, it is even be illegal to have this tracker without a privacy policy and an opt-out possibility. So everyone running a Volumio for other people to use is actually breaking the law in the EU.

> As I said many times, if someone if willing to help develop this, please let us know.

I can surely open a PR just to remove the tracker :man_shrugging: that should be the sane default anyway.

**Comment by STPKITT** [comment]
Sounds great, I'm really looking forward to that and then being able to fully recommend Volumio again.

**Comment by oisteink** [comment]
I'm not sure beeing low on developers are a good enough reason to keep trackers in software, but I'm not a law person. It's surely not that many lines to change to remove both GA and the FB pixel, and then re-implement once there is enough resources to do a proper opt-in staying in line with current legislation.

as MyVolumio is a paid service, tracking your users without opt-in seems to me like a bad business decicion. All you need is one pissed off user or some stiff competition to give you quite the head-ache.

Opinion: How you use the data is not really intresting in this context, as it does not make it excempt from GDPR policy. The quality of the data is probably low as quite a lot will be using browsers or pi-holes that block this tracking.

**Comment by volumio** [comment]
@oisteink thanks, yours has been the only useful controbution to the matter. 
We are working on it

**Comment by volumio** [comment]
Since we did not find a way yet to implement a proper opt-out mechanism, we removed GA and FB trackers. They will reapper once we find a proper way for users to opt out.

See https://github.com/volumio/Volumio2-UI/commit/f41c1c97c93bffbe2c8cd2623f4b9f1ef41df9e7

**Comment by arthurlutz** [comment]
@volumio thanks a lot ! I'm glad this issue is resolved in this way and I hope you find alternative and privacy respecting ways to replace this functionality.

**Comment by dup2** [comment]
Thanks, appreciated.

**Comment by volumio** [comment]
We reintroduced those since we found an effective and privacy-respecting way to add an opt out function (it can be found in settings -> privacy settings).
For anyone interested in the technical implementations, those are the commits:
https://github.com/volumio/Volumio2/commit/33642365f6069a578ebfc66f92fb4750e813e6a2
https://github.com/volumio/Volumio2-UI/commit/9766f97ae12d8928489e5cb71fa8519fa67e8ba2

Any feedbacks, suggestions or PRs are welcome

**Comment by jalr** [comment]
1. opt-out is never a privacy-respecting way

2. https://github.com/volumio/Volumio2/commit/33642365f6069a578ebfc66f92fb4750e813e6a2#diff-a49cb4822831b4b4ab0ad79766d0fa76R349
> Facebbook Pixel and Google Analytitcs

Now tell me these typos are there by accident. You've got to be kidding me! Sorry but you're trying too hard to palm the tracking crap off on your users.

**Comment by dup2** [comment]
Can not understand this neither, this is a real mess. Why even two trackers? Why not opt-in? While I can see your business model trying to sell premium subscription and hardware which I can understand somehow, tracking users this way and also placing your paid offer prominently on the free and open source version UI is not ok IMHO. Please learn from the gitlab disaster about tracking UI activity.

**Comment by volumio** [comment]
I would suggest anyone participating this conversation to:
- Replace "you guys do this crap and that crap and track this fuck you" with "I think this can be solved like this, by doing this like that, by implementing this". (I gave up requesting pull requests seems everyone in this conversation is more interested in grepping his 3 lines of code instead of doing something useful to the community, at least maybe someone can still write educated suggestions?).
- Before writing any further sentence. Consider that Volumio is a project that involves around 20 people (some of them on Volumio payroll), working hard to deliver something that you use everyday for FREE (and we work as hard as we cann to keep it FOSS as much as possible). 
- The reason why we push freemium services is because running this project costs lot of money and basically NO-ONE donates (230k people use it, less than 100 per year donate).

Hope this conversation gets more constructive from now on

**Comment by dup2** [comment]
ok, I understand your point here, let's get back to an objective discussion. Please do not get upset about your community when touching such sensitive topics as privacy.

The opener of this issue @arthurlutz pointed out 3 solutions, please check the first post here. I'd support his order of preference, I personally strongly prefer option 2 if you need this trackers for any purpose.

**Comment by volumio** [comment]
@dup2 thanks for bringing it back to an objective discussion, as you rightfully point out this is a sensitive topic. The only way to find a solution that makes everyone happy is to consider all points of views involved.

I can see that option 2 might be preferable, but 2 was IMHO was the best compromise we could come up with (and it has been regarded as acceptable solution by almost anyone in this discussion).

The reason for N3 being discarded has been that this privacy feature has been requested by a minority of our users. To have an opt-in we should have added another step in the first config wizard (could not go anywhere else, if opt-in). This is something we would rather avoid, as we want the first config as simple and straightforward as possible (we are also soon removing the donation button for the very same reason).

My understanding is that the whole point here was to offer a simple and effective way to ensure no tracking is active for who wishes so. The implementation we've done ensures that not even the libraries are loaded and that the choice is persistent among updates. 
If we were to use opt-in, where would you place it on the UI ?(remember that those analytics are quite useful for us, even if we don't track any personal information, just visited URLs within the UI)

**Comment by STPKITT** [comment]
My comment on this from October 2019 is still valid I just wanted to add this:
I'd never buy a 400 EUR+ audio player on which I need to opt-out of tracking.
I'd also never subscribe or donate to any service that is promoting Facebook and Google Analytics which you do.
I do not know the composition of your current customer base and your target audience but if those consist in a big part of FOSS enthusiasts I imagine you risk loosing them if you not go for the opt-in or no tracking by shady companies at all.
Also having just opt-in or no tracking at all also offers the chance to set Volumio apart.
Btw regarding not offering the opt-out option in the first config wizard: wouldn't that mean that every user is tracked at least once btw?

**Comment by volumio** [comment]
2 things:
- We don't promote GA of FB, we just use them. It's different.
- The discussion on first config wizard was about opt-in, not opt out.

**Comment by STPKITT** [comment]
- Anyone using Facebook and Google services promotes them or help them grow if that's the better english wording for that.

- True! Sorry! I mixed that up.

**Comment by acidicX** [comment]
> opt-out is never a privacy-respecting way

This is especially true in terms of the GDPR.

I don't think an opt-out will make users (in the sense of owners of the instance) understand that if they don't opt-out, they **must** set up a privacy policy (legal document) and have their end-users accept it if the end-users use the owners volumio instance. This is what the GDPR requires if you use 3rd party data services @volumio.

> I do not know the composition of your current customer base and your target audience but if those consist in a big part of FOSS enthusiasts I imagine you risk loosing them if you not go for the opt-in or no tracking by shady companies at all.

:100: right on the spot. I would not recommend any OSS to friends that does use dark patterns like tracking opt-outs hidden somewhere.

**Comment by oisteink** [comment]
`var allowUIStatistics = self.config.get('allow_ui_statistics', true);`
Does this mean that if there is no setting you default to collecting statistics?

I still don't trust this, and have no idea why you'd need facebook and google to figure out how people are using the UI. I will keep on stripping the code out and be carefull with updates.

I've also stopped recomending Volumio to friends for now, and stopped the one project I had for a friend. Went with a system using Roon for him as they have a privacy system I'm comfortable with.
