### ISSUE TITLE
Status while reading music library

### ISSUE THREAD

**Issue by kaffeeringe** [volumio/Volumio2-UI#513]
I added my music library via nfs but I don't see any progress in reading the library until it's finished. As my library is rather big, it takes a very long time and I never know if Volumio is still doing anything. It world be great if there was a status bar or if it shows how many tracks are already indexed or if it's reading anything at all.

**Comment by xipmix** [comment]
Strange, in 'my music' I can see the numbers of albums, artists, tracks & playtime all incrementing while it scans a new NFS mount. I also get a popup telling me the scan has started. version 2.389 on pi.
A status bar requires knowing where the end is, ie how many files in total, which is tricky in this context. If your track count is not incrementing, probably nothing is happening. You should also see
```
$ sudo journalctl -f
Jun 20 12:25:06 volumio volumio[1297]: info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
Jun 20 12:25:10 volumio volumio[1297]: info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
...etc...
```
Perhaps it would help the UI to have a display element on the statistics line that acts like a 'spinner', showing the elapsed time while the scan is ongoing, but otherwise does not appear. asciiart:
```
Artists       Albums      Tracks      Playtime              Scantime
     82           86         276      17:44:37              00:03:45
```
It might also be useful to change the color of the 'Update' or 'Rescan' button while an Update or Rescan is active.

**Comment by robcee** [comment]
We could do a file count before processing the library. That would give us a rough number to render a status bar against.

**Comment by xipmix** [comment]
Yep, that is a possibility. How do you see the display of the progress being done, in the case where it takes many minutes to do the scan? I'm wondering if the user will want to have a modal popup hanging around for that long. I guess this affects my proposal also, though. I was imagining you could start the scan and change to another UI window (eg playback) and come back later to check on progress, but perhaps that's not possible and one really does need to hang out in the MyMusic window until the scan is done.
