### ISSUE TITLE
FOLDER NAMES CUT OFF IN MUSIC LIBRARY

### ISSUE THREAD

**Issue by Eraserded** [volumio/Volumio2-UI#770]
Since about the last 3-4 updates, I get the folder names cut off in Music Library view. 
It is limiting the number of text characters for some reason even thought there is much more space on screen.
Makes it hard to know what version when I have more than one (see attached).
Not sure exactly what update did this but before I could see the entire folder name.
I recall that the update that did this also made text and also the thumbnail views look smaller if that is a clue.
I believe I updated 3 times since March including last weeks revision.

**Comment by xipmix** [comment]
what version are you on now please? I can check my older version to see if I see the problem or not.
Also, your attached picture didn't come through, could you try uploading it again?

**Comment by Eraserded** [comment]
Hello,

We are now on 2.846 beta v.
We are testing this version with new plugins implementation
Hoping to release official one within next days

Thanks

Davide
Volumio tech support

Il giorno sab 24 ott 2020 alle ore 08:16 xipmix <notifications@github.com>
ha scritto:

**Comment by volumio** [comment]
@bencehusi could you please give it a look?

**Comment by Eraserded** [comment]
> what version are you on now please? I can check my older version to see if I see the problem or not.
> Also, your attached picture didn't come through, could you try uploading it again?
[fwdvolumioprimoissue.zip](https://github.com/volumio/Volumio2-UI/files/5469542/fwdvolumioprimoissue.zip)

**Comment by xipmix** [comment]
On 2.777 I see all directories displayed ok, the longest is 64 characters.

**Comment by bencehusi** [comment]
From what I can see, this issue appears when navigating in list-view (see attached image). Is it what we are talking about?
<img width="1062" alt="Screenshot 2020-11-03 at 10 02 56" src="https://user-images.githubusercontent.com/10700975/97966685-76419a00-1dbc-11eb-8d44-7060bccaf98e.png">

This is due to the arbitrary meta information that might or might not appear with these rows:
<img width="1208" alt="Screenshot 2020-11-03 at 10 06 15" src="https://user-images.githubusercontent.com/10700975/97966676-72157c80-1dbc-11eb-8f69-28a119807445.png">

I'll have a look and see what we can do about it.

**Comment by bencehusi** [comment]
A fix is underway with the next release.
