### ISSUE TITLE
[2.915 on Pi 2] UI not accessible, ssh works

### ISSUE THREAD

**Issue by Stooovie** [volumio/Volumio2-UI#801]
Clean install of 2.915 has inaccessible UI. It only worked on first boot. After connecting to wifi, I can ssh into it (i have enabled ssh on first run), but that's it. UI is completely inaccessible, either via 192.168.0.XXX or volumio.local. Both work for ssh.

**Comment by volumio** [comment]
Sorry you're having this issue. Since you have SSH access, do you mind pastng here the complete output of 

sudo journalctl 

Thanks 

PS: Do the /dev interface work? If yes can you send a log and paste the output here?

**Comment by Stooovie** [comment]
Hi, thanks. The complete output is [here](https://pastebin.com/kSiKc1gP).

What do you mean with "Do the /dev interface work"?

**Comment by volumio** [comment]
Hi. That does not appear to be a fresh install. The problem is caused by a plugin, music shield, 

Oct 04 11:42:51 volumio sudo[1127]: pam_unix(sudo:session): session closed for user root
Oct 04 11:42:52 volumio volumio[1075]: info: Applying required configuration parameters for plugin music_services_shield
Oct 04 11:42:52 volumio volumio[1075]: /bin/sh: 1: /data/plugins/miscellanea/music_services_shield/setconfigparameter.sh: Perm
Oct 04 11:42:52 volumio volumio[1075]: child_process.js:644
Oct 04 11:42:52 volumio volumio[1075]: throw err;
Oct 04 11:42:52 volumio volumio[1075]: ^
Oct 04 11:42:52 volumio volumio[1075]: Error: Command failed: /data/plugins/miscellanea/music_services_shield/setconfigparamet
Oct 04 11:42:52 volumio volumio[1075]: /bin/sh: 1: /data/plugins/miscellanea/music_services_shield/setconfigparameter.sh: Perm
Oct 04 11:42:52 volumio volumio[1075]: at checkExecSyncError (child_process.js:601:13)
Oct 04 11:42:52 volumio volumio[1075]: at execSync (child_process.js:641:13)
Oct 04 11:42:52 volumio volumio[1075]: at musicServicesShield.writeConfigParameter (/data/plugins/miscellanea/music_services_s
Oct 04 11:42:52 volumio volumio[1075]: at musicServicesShield.writeAllConfigParameters (/data/plugins/miscellanea/music_servic
Oct 04 11:42:52 volumio volumio[1075]: at musicServicesShield.onVolumioStart (/data/plugins/miscellanea/music_services_shield/
Oct 04 11:42:52 volumio volumio[1075]: at PluginManager.loadCorePlugin (/volumio/app/pluginmanager.js:171:38)
Oct 04 11:42:52 volumio volumio[1075]: at /volumio/app/pluginmanager.js:250:34
Oct 04 11:42:52 volumio volumio[1075]: at Array.forEach (<anonymous>)
Oct 04 11:42:52 volumio volumio[1075]: at HashMap.<anonymous> (/volumio/app/pluginmanager.js:249:20)
Oct 04 11:42:52 volumio volumio[1075]: at HashMap.forEach (/volumio/node_modules/hashmap/hashmap.js:171:10)
Oct 04 11:42:52 volumio systemd[1]: volumio.service: main process exited, code=exited, status=1/FAILURE

1) Did you install this plugin? after first boot?
2) Where did you got this plugin?

Can you provide more info about this install? is it really fresh? When do you install this plugin?

**Comment by Stooovie** [comment]
It is a completely new install from this morning, done with Balena Etcher and without restoring backup. I did install the Shield addon after the initial config as I was using it before this update (up until yesterday when I noticed the broken web radios). I can try again without installing it. 

So 1) yes, at first boot 
2) in Volumio's default plugin store

**Comment by Stooovie** [comment]
SOLUTION: Looks like the plugin Music Services Shield was the culprit. Seems like a new bug to me as I always had it installed and it never made any issues. But it works now. Thanks!

**Comment by volumio** [comment]
Thanks for reporting, we will contact the developer and ask him to fix his plugin

**Comment by petecallaghan** [comment]
Hi I will take a look at the fault in MusicServicesShield

**Comment by petecallaghan** [comment]
Please note that version 1.2.1 does not seem to have been released for Pi or Tinkerboard on the OTA service. Can you update this first please @volumio

**Comment by volumio** [comment]
@balbuze when you have time can you update the plugin (if this update solves the issue)

**Comment by petecallaghan** [comment]
In the meantime I will look at changes to index.js as requested.

**Comment by petecallaghan** [comment]
Pull request issued. https://github.com/volumio/volumio-plugins/pull/629

**Comment by balbuze** [comment]
I disabled the plugin from the list, waiting for the fix

**Comment by balbuze** [comment]
done ;-)
